CREATE TABLE KH_STUDENT (
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE,
	CLUB_NO REFERENCES KH_CLUB
);

CREATE TABLE KH_CLUB (
	CLUB_NO NUMBER PRIMARY KEY,
	CLUB_NAME VARCHAR2(30) UNIQUE,
	CAPACITY NUMBER NOT NULL,
	EC_YN CHAR(1) CHECK(EC_YN IN ('Y','N')),
	ACTIVITY_TYPE VARCHAR2(100)
);

COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';
COMMENT ON COLUMN KH_STUDENT.CLUB_NO IS '동아리 번호';

COMMENT ON COLUMN KH_CLUB.CLUB_NO IS '동아리 번호';
COMMENT ON COLUMN KH_CLUB.CLUB_NAME IS '동아리 이름';
COMMENT ON COLUMN KH_CLUB.CAPACITY IS '정원';
COMMENT ON COLUMN KH_CLUB.EC_YN IS '대외 활동 여부';
COMMENT ON COLUMN KH_CLUB.ACTIVITY_TYPE IS '활동성격';

CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;
CREATE SEQUENCE SEQ_CLUB_NO NOCACHE;

INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '시그마', 25, 'N', '수학 연구 및 문제 풀이 스터디');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '하모니밴드', 20, 'Y', '음악 밴드, 교내 공연 중심');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '디버그', 30, 'N', '프로그래밍 개발 스터디');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '도담', 20, 'N', '독서 및 문학 토론 동아리');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '클라우드', 30, 'Y', '클라우드·AI 프로젝트 대회 참가');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '네버기브업', 40, 'Y', '교내 스포츠·헬스 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '아르테', 25, 'N', '미술·디자인 전시 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '프론티어', 45, 'N', '여행 및 산악 탐험');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '라온', 25, 'Y', '댄스·공연 동아리');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '새벽빛', 30, 'Y', '사진전·영상제 외부 참여');

SELECT * FROM KH_CLUB;
COMMIT;

INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이현우', 25, '의학과', '2019-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김도현', 26, '기계공학과', '2019-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최예린', 25, '컴퓨터공학과', '2019-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '정하은', 25, '심리학과', '2019-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이서연', 24, '디자인학과', '2020-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오지민', 24, '수학과', '2020-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '신재현', 25, '화학공학과', '2020-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '장현우', 28, '건축학과', '2020-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박서연', 24, '간호학과', '2020-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '송지호', 24, '컴퓨터공학과', '2020-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤하은', 24, '경영학과', '2020-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '조민재', 24, '물리학과', '2020-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤서진', 26, '국어국문학과', '2020-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박상민', 27, '치의학과', '2020-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '문지우', 24, '심리학과', '2020-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김하늘', 24, '간호학과', '2020-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오세훈', 23, '의학과', '2021-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '장도현', 23, '수학과', '2021-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '하은호', 25, '영어영문학과', '2021-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '백서윤', 23, '기계공학과', '2021-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이준호', 24, '무역학과', '2021-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이재명', 22, '정치외교학과', '2022-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이현상', 22, '경제학과', '2022-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박도영', 22, '컴퓨터공학과', '2022-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김유나', 23, '경영학과', '2022-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이서윤', 22, '수학과', '2022-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이윤아', 21, '물리학과', '2023-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박민준', 24, '화학공학과', '2023-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '임수빈', 21, '간호학과', '2023-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이지아', 22, '국어국문학과', '2023-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최연우', 20, '영어영문학과', '2023-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박유진', 20, '경영학과', '2024-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '허예은', 21, '심리학과', '2024-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '연준서', 20, '경제학과', '2024-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '남궁소율', 22, '무역학과', '2024-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '계백순', 20, '신문방송학과', '2024-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤시은', 20, '디자인학과', '2024-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최아린', 19, '간호과', '2025-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최은서', 20, '의학과', '2025-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이도윤', 19, '건축학과', '2025-03-02', 2);

COMMIT;

SELECT * FROM KH_STUDENT;



































